export type HelpTopic = {
  slug: string;
  title: string;
  eyebrow: string;
  summary: string;
  status: "Live" | "Tested locally" | "Implemented" | "Policy";
  functions: string[];
  howTo: string[];
  engine: string;
  routes: string[];
  rights: string;
  limitations: string[];
};

export const helpTopics: HelpTopic[] = [
  {
    slug: "start-here",
    title: "Start here",
    eyebrow: "Guide 01",
    summary: "A plain-language map of GravelKing Pro, its four production pillars, and the evidence labels used throughout this guide.",
    status: "Live",
    functions: ["Choose a production tool", "See the access level for each workflow", "Read the difference between tested behavior and a claim that still needs production verification"],
    howTo: ["Open Help from the main navigation.", "Choose a topic or use the full tool index.", "Follow the steps on the tool page and keep the returned file, certificate ID, or verification result with your project records."],
    engine: "GravelKing Pro web application with the Morris Law Kernel V3.5 mastering path and browser audio tools.",
    routes: ["/help", "/help/start-here"],
    rights: "The guide explains evidence and provenance; it does not transfer copyright or replace a registration, license, contract, or legal advice.",
    limitations: ["A feature marked Implemented is not automatically proven live in the public deployment.", "A certificate supports a record of provenance but does not decide ownership or infringement."],
  },
  {
    slug: "mastering",
    title: "Mastering",
    eyebrow: "Tool 02",
    summary: "Upload an audio file, select a target, and receive a mastered WAV produced by the Morris Law Kernel V3.5.",
    status: "Tested locally",
    functions: ["Accept common audio containers", "Choose a mastering preset and intensity", "Use optional denoise, sidechain, stereo-link, adaptive, and auto-threshold controls", "Receive a full master or an entitled preview"],
    howTo: ["Open Mastering.", "Upload a file and choose a preset.", "For an IP record, turn on certification and enter the artist name and creative direction.", "Download the returned WAV and retain its certificate ID when certification is enabled."],
    engine: "Python Morris Law Kernel V3.5 through the remote kernel when configured, with the same-kernel local worker as fallback. FFmpeg is ingest and preparation plumbing, not a mastering fallback.",
    routes: ["POST /api/kernel/master", "GET /api/subscription/status"],
    rights: "Plain mastering does not assert ownership. Certification is opt-in and records the submitted asset, artist assertion, creative direction, and a split cryptographic marker.",
    limitations: ["Full-length free usage is limited; paid tiers unlock the applicable unlimited path.", "A master is not proof that the uploader owned every source element.", "Real public production audio verification remains a separate operational check."],
  },
  {
    slug: "mastering-presets",
    title: "Mastering presets and controls",
    eyebrow: "Sub-tool 03",
    summary: "Understand what the mastering controls change and what the kernel reports back.",
    status: "Implemented",
    functions: ["Select Baseline, Vocal Air / Crisp Highs, Normal, Broadcast, Tape Warmth / Saturation, Vocal Punch / Phase Focus, Sub Low-End / Kick Weight, Film, Final Gain / Ceiling (−14.0 LUFS), SoundCloud, or Apple Music targets", "Set intensity from 0–100", "Set detector filter and frequency", "Choose stereo-link and adaptive mode", "Enable auto-threshold and review detected RMS/applied threshold when returned"],
    howTo: ["Start with Normal or Baseline.", "Use a platform target only when it matches your delivery requirement.", "Enable auto-threshold when you want the kernel to measure the source before choosing the threshold.", "Compare the returned output and keep the processing headers with the session record."],
    engine: "Kernel preset mapping plus Python DSP parameters for EQ, saturation, adaptive sidechain compression, limiting, and LUFS staging.",
    routes: ["POST /api/kernel/master"],
    rights: "Control choices are production metadata. They do not create ownership by themselves.",
    limitations: ["A preset is a starting point, not a guarantee of translation on every playback system.", "A future UI status can be implemented before its public deployment is verified."],
  },
  {
    slug: "vocal-booth",
    title: "Vocal Booth",
    eyebrow: "Tool 04",
    summary: "Load a backing track, display lyrics, record a vocal take with monitor effects, preview the take, and export a mix containing the backing and recorded vocal.",
    status: "Implemented",
    functions: ["Load a backing track", "Load lyrics from the studio library or enter them manually", "Record through the browser microphone", "Monitor with vocal presets", "Preview the recorded take", "Mix the backing and recorded vocal"],
    howTo: ["Open Vocal Booth and add a backing track.", "Enter or load lyrics.", "Choose a monitor preset, arm the microphone, and record.", "Preview the take, then export the mix when satisfied.", "Confirm that the guide vocal is muted from the export before sharing the file."],
    engine: "Browser MediaRecorder and Web Audio monitoring, with the Morris Law Kernel V3.5 for backing-track mastering and the server studio mix route for export.",
    routes: ["POST /api/kernel/master", "POST /api/kernel/studio-mix", "POST /api/audio/transcribe", "GET /api/library/studio"],
    rights: "Your lyrics, recorded performance, and original arrangement may support your own rights when you created them and have rights to the backing material. A guide or uploaded source remains subject to its owner’s terms.",
    limitations: ["The exported mix excludes the guide vocal.", "Energy timing is approximate; synced lyric timing is labeled when available.", "Mixdown requires the applicable studio entitlement."],
  },
  {
    slug: "vocal-recording",
    title: "Vocal recording and monitor effects",
    eyebrow: "Sub-tool 05",
    summary: "Record a take with the selected monitor processing baked into the captured performance path.",
    status: "Implemented",
    functions: ["Request microphone access", "Show an input level meter", "Start and stop a take", "Apply monitor presets", "Reset and re-record", "Play the take back with the backing track"],
    howTo: ["Use headphones when possible to reduce acoustic bleed.", "Allow microphone access only for the current recording.", "Set a comfortable input level before recording.", "Stop the take, preview it, and re-record if the performance or timing needs work."],
    engine: "useVocalBoothRecorder plus Web Audio monitor graph and local browser playback.",
    routes: ["Browser microphone APIs", "POST /api/kernel/studio-mix"],
    rights: "The recorded performance is a separate creative contribution. Keep the original take and session details if you need to establish when and how it was made.",
    limitations: ["Browser microphone permissions and device quality affect the recording.", "The system cannot grant rights to a backing track that you did not license."],
  },
  {
    slug: "studio-mix",
    title: "Studio mix and arrangement",
    eyebrow: "Sub-tool 08",
    summary: "Combine uploaded tracks sequentially or in layers and process the resulting mix through MLK v3.",
    status: "Tested locally",
    functions: ["Upload multiple tracks", "Choose sequential or layered arrangement", "Set speed and pitch bounds", "Apply supported noise reduction", "Return a WAV mix with kernel/parity headers"],
    howTo: ["Add one or more audio tracks.", "Choose Layer for simultaneous playback or Sequential for a timeline chain.", "Review duration limits before processing.", "Download the WAV only after checking the arrangement and levels."],
    engine: "FFmpeg for arrangement and format normalization, then ffmpeg-native MLK v3 carve for safe streaming execution.",
    routes: ["POST /api/kernel/studio-mix"],
    rights: "You must have permission for every track you upload and combine. The mix record can document your arrangement but cannot cure an unauthorized sample.",
    limitations: ["MIDI is rejected without a soundfont path.", "Combined duration and upload limits apply.", "This is an arrangement workflow, not a confirmed dedicated Diffin engine."],
  },
  {
    slug: "songwriting",
    title: "Songwriting Studio",
    eyebrow: "Tool 09",
    summary: "Generate a lyric draft from your direction, edit it line by line, and keep a record of the human changes.",
    status: "Implemented",
    functions: ["Write a story or concept", "Choose genre and musical details", "Generate a draft", "Edit individual lines", "Request controlled variations", "Save a project"],
    howTo: ["Enter your own concept and constraints.", "Generate a draft, then review every line.", "Edit, delete, or replace lines to make the work your own.", "Save the project and use the authorship view before certifying."],
    engine: "Gemini-backed lyric generation where configured, shared authorship scoring, project persistence, and safety validation.",
    routes: ["POST /api/lyrics/generate", "POST /api/lyrics/remix", "POST /api/lyrics/save"],
    rights: "Human-written expression and meaningful human edits can matter to a copyright claim. Generated text may have limitations under the source provider’s terms; review the source terms and do not claim exclusive rights automatically.",
    limitations: ["The tool does not guarantee that a generated phrase is unique.", "Do not request recognizable copyrighted lyrics or imitate a living artist."],
  },
  {
    slug: "lyrics-editing",
    title: "Lyrics editing and safety",
    eyebrow: "Sub-tool 10",
    summary: "Use the line editor, rhyme suggestions, and controlled variations without hiding the human contribution.",
    status: "Implemented",
    functions: ["Edit a line", "Generate bounded variations", "Search rhyme suggestions", "Mark human-edited lines", "Export a readable lyric record"],
    howTo: ["Keep the original generated draft.", "Make edits directly in the line editor.", "Use suggestions as options, not as a substitute for review.", "Reject any output that is unsafe, copied, or not yours."],
    engine: "Diff-match-patch-based final-text comparison and server-side safety/ownership workflow.",
    routes: ["POST /api/lyrics/remix", "POST /api/lyrics/rhyme"],
    rights: "The record distinguishes the generated draft from the final text so your creative contribution can be documented. It is evidence, not a legal ruling.",
    limitations: ["A score can be affected by the final text and comparison method.", "Delete-and-retype of identical text does not create artificial authorship credit."],
  },
  {
    slug: "authorship",
    title: "Authorship scoring",
    eyebrow: "Tool 11",
    summary: "Compare an original draft with the final lyric text and return a 0–100 human-authorship score.",
    status: "Tested locally",
    functions: ["Compare original draft and final text", "Credit inserted human text", "Credit deleted draft text partially", "Recognize structural moves", "Apply the eligibility threshold used by the project"],
    howTo: ["Keep the unedited draft unchanged.", "Make and save real creative edits.", "Review the score and breakdown.", "Do not manipulate the record or claim the score is a court finding."],
    engine: "Shared @workspace/authorship library using diff-match-patch semantic diffing.",
    routes: ["POST /api/lyrics/authorship", "POST /api/lyrics/certify"],
    rights: "The score helps organize evidence of human contribution. It does not create copyright, guarantee registration, or decide a dispute.",
    limitations: ["Identical final text scores zero human contribution against the draft.", "The threshold is a product rule, not a substitute for legal analysis."],
  },
  {
    slug: "ip-certificates",
    title: "IP certificates",
    eyebrow: "Tool 12",
    summary: "Create a cryptographic provenance record for a certified master or lyric project when you affirm that you have the necessary rights.",
    status: "Implemented",
    functions: ["Opt in to certification", "Record artist and creative direction", "Store a content hash and certificate ID", "Embed the public half of the marker", "Back up the server record", "Retrieve a certificate record or PDF"],
    howTo: ["Only certify material you are authorized to submit.", "Enter accurate artist and creative-direction information.", "Save the certificate ID and exported file together.", "Use Verify when you need to check the signal later."],
    engine: "SHA-256 content binding, split nominator/denominator design, HMAC handshake, PostgreSQL record, and Firestore backup.",
    routes: ["POST /api/kernel/master with certify=true", "GET /api/court-cert/:certId", "GET /api/court-cert/:certId.pdf"],
    rights: "A certificate is a dated technical record supporting provenance. It does not transfer rights, register a copyright, prove exclusive ownership, or guarantee a court result.",
    limitations: ["The private denominator is server-side and cannot be reconstructed from the file alone.", "False ownership assertions can lead to account review and certificate distrust."],
  },
  {
    slug: "verify",
    title: "Verify and fingerprint",
    eyebrow: "Tool 13",
    summary: "Check whether a certified signal and its server record remain consistent.",
    status: "Implemented",
    functions: ["Submit a certified signal for verification", "Read anchor and HMAC status", "Check a certificate ID", "Review ingestion and uniqueness checks"],
    howTo: ["Open Verify.", "Upload the file or provide the requested certificate reference.", "Read the result as VALID, TAMPERED, or NO_WATERMARK.", "Keep the result with the file and the original certificate record."],
    engine: "Signal-level marker extraction, HMAC comparison, SHA-256 binding, metadata screening, loudness checks, and near-silence/clipping checks.",
    routes: ["POST /api/v1/verify", "POST /api/kernel/verify-signal", "GET /api/court-cert/:certId"],
    rights: "Verification can show whether a certified signal matches its record. It does not identify every possible infringer or prove legal ownership by itself.",
    limitations: ["Plain masters without certification have no IP marker to verify.", "Fingerprint checks are technical screening, not a universal similarity guarantee."],
  },
  {
    slug: "downloads",
    title: "Downloads and delivery",
    eyebrow: "Tool 14",
    summary: "Save processed audio through short-lived, signed delivery links and keep paid full-length files behind entitlement checks.",
    status: "Tested locally",
    functions: ["Download mastered WAV files", "Receive short-lived delivery tokens", "Use direct browser downloads", "Apply free preview and paid full-length rules", "Retrieve order-linked files where eligible"],
    howTo: ["Wait for processing to finish.", "Use the Download control rather than copying an internal path.", "Save the file promptly because delivery tokens expire.", "If access is denied, review the plan or order status instead of retrying with altered parameters."],
    engine: "Signed HMAC download tokens, server-side entitlement and usage checks, temporary file cleanup, and direct response streaming.",
    routes: ["GET /api/download/:token", "GET /api/tracks/:id/download"],
    rights: "A download receipt documents delivery; it does not prove the source material was authorized.",
    limitations: ["Full-length master access is paid or allowance-gated.", "Expired, altered, or cross-session tokens are rejected."],
  },
  {
    slug: "convert",
    title: "Convert",
    eyebrow: "Tool 15",
    summary: "Convert supported audio and media containers into a usable production format.",
    status: "Implemented",
    functions: ["Upload supported media", "Normalize sample rate and channel layout", "Return a downloadable converted file", "Use converted files in mastering or studio workflows"],
    howTo: ["Choose Convert.", "Upload a file you have permission to process.", "Select the requested output settings.", "Check the returned file before using it in another workflow."],
    engine: "FFmpeg format conversion and audio guards; conversion is not presented as mastering.",
    routes: ["POST /api/convert"],
    rights: "Conversion changes format, not ownership or licensing.",
    limitations: ["Container, duration, and size limits apply.", "Conversion cannot restore information lost in a lossy source."],
  },
  {
    slug: "label",
    title: "Label and library",
    eyebrow: "Tool 17",
    summary: "Organize submitted tracks, review library records, and prepare customer-facing artist information.",
    status: "Implemented",
    functions: ["View library items", "Review artist and track records", "Check submission eligibility", "Open certificate and verification records"],
    howTo: ["Sign in before opening Library or Label.", "Use the track record as the source of truth for status.", "Submit only material you control or are authorized to submit.", "Use the contact path for rights disputes or corrections."],
    engine: "PostgreSQL track records, entitlement checks, certificate linkage, and customer library routes.",
    routes: ["GET /api/library", "GET /api/tracks", "GET /api/tracks/submit-eligibility"],
    rights: "The label workflow is an administrative record, not a transfer of copyright or a guarantee of release acceptance.",
    limitations: ["Admin review tools are separate and unavailable to ordinary customer accounts.", "A record can be corrected or removed after a substantiated rights issue."],
  },
  {
    slug: "submit",
    title: "Track submission",
    eyebrow: "Sub-tool 18",
    summary: "Submit an authorized track for review with the metadata and files needed for a clear record.",
    status: "Implemented",
    functions: ["Check eligibility", "Submit track metadata", "Attach an authorized audio asset", "View submission status", "Respond to review outcomes"],
    howTo: ["Confirm you have rights to the track and all samples.", "Complete metadata accurately.", "Submit the file and keep the confirmation.", "Respond promptly if the review team requests clarification."],
    engine: "Track submission route, validation middleware, PostgreSQL records, and admin review workflow.",
    routes: ["GET /api/tracks/submit-eligibility", "POST /api/tracks/submit", "GET /api/tracks"],
    rights: "Submitting a track is an assertion that you have the rights needed for the requested use. It is not a rights grant from GravelKing Pro.",
    limitations: ["False metadata or unauthorized uploads can trigger review, removal, suspension, or a ban.", "Review status is not legal clearance."],
  },
  {
    slug: "account",
    title: "Account and access",
    eyebrow: "Tool 19",
    summary: "Understand sign-in, entitlement, session persistence, customer access, and the boundary between customer and admin tools.",
    status: "Tested locally",
    functions: ["Sign in with email or a social provider", "Use the fixed reviewer demo sign-in", "View current plan and tier", "Sign out", "Keep customer access separate from admin access"],
    howTo: ["Use Sign in for the normal account flow.", "Use the reviewer route only when you have been given the reviewer credentials.", "Check the plan badge before starting a paid workflow.", "Sign out from Account when using a shared review device."],
    engine: "Clerk session handling plus the reviewer-only password session and entitlement lookup.",
    routes: ["GET /api/subscription/status", "POST /api/demo/login"],
    rights: "Account access does not change copyright ownership. Keep credentials private and do not share a session cookie.",
    limitations: ["The reviewer demo account is customer-only and must never be used to access admin operations.", "The public deployment must be republished before a newly added reviewer route is available there."],
  },
  {
    slug: "pricing",
    title: "Plans and checkout",
    eyebrow: "Tool 20",
    summary: "Review plan entitlements and use the payment flow to unlock the customer tools included in your plan.",
    status: "Implemented",
    functions: ["Review current plan names and prices", "Start checkout", "Read current entitlement", "Use paid tools after activation"],
    howTo: ["Open Pricing.", "Choose the plan that matches your production needs.", "Complete the in-app payment form.", "Confirm the plan badge before uploading a full-length file."],
    engine: "Stripe Payment Element, webhook synchronization, PostgreSQL entitlement state, and live API fallback when the mirror is delayed.",
    routes: ["GET /api/stripe/products", "POST /api/stripe/create-subscription-intent", "GET /api/subscription/status", "POST /api/stripe/webhook"],
    rights: "Payment grants service access under the plan terms; it does not grant rights in uploaded or generated content.",
    limitations: ["Subscription status can take a short time to synchronize.", "Plan access does not override upload authorization or service rules."],
  },
  {
    slug: "user-rules",
    title: "Service user rules",
    eyebrow: "Policy 21",
    summary: "The rules for honest use of GravelKing Pro, account review, suspension, and bans.",
    status: "Policy",
    functions: ["Set rights and authorization expectations", "Prohibit manipulation and abuse", "Explain account review", "Explain suspension and ban authority", "Provide a correction and contact path"],
    howTo: ["Use only files, lyrics, performances, and metadata you own or are authorized to use.", "Make truthful ownership and authorship statements.", "Do not bypass email gates, usage limits, payment gates, tokens, verification, or moderation.", "Do not reverse engineer, scrape, overload, impersonate, or attack the service.", "Report a suspected error or rights dispute through Contact."],
    engine: "Server-side authorization, rate limits, signed tokens, validation, audit records, admin review, and account-level entitlement controls.",
    routes: ["Applies across all authenticated and upload routes", "GET /api/account or Contact for support"],
    rights: "By using the service, you agree that GravelKing Pro may review activity and records when it reasonably suspects fraud, abuse, unauthorized content, security threats, or a rights violation.",
    limitations: ["Review is not a finding of legal liability.", "GravelKing Pro may suspend or ban access, remove material, invalidate a certificate, or limit features when rules are violated or continued access creates a security, rights, or service risk, subject to applicable law and any required notice or appeal process.", "No user may use a certificate or service record as a false legal claim."],
  },
  {
    slug: "ip-rights",
    title: "IP rights and evidence",
    eyebrow: "Policy 22",
    summary: "What GravelKing Pro records can support, what they cannot promise, and how to preserve a stronger provenance trail.",
    status: "Policy",
    functions: ["Separate human contribution from generated drafts", "Bind a certified file to a content hash", "Store a server-side certificate record", "Verify later whether the certified signal changed", "Export a readable record for counsel or a rights file"],
    howTo: ["Keep original drafts, source files, session dates, licenses, and exported results.", "Certify only after checking the source rights.", "Keep the certificate ID with the exact file it describes.", "Use Verify before making a provenance statement to another party.", "Consult a qualified attorney for registration, licensing, disputes, and enforcement."],
    engine: "Authorship diffing, SHA-256 hashes, split signal/server anchors, HMAC binding, database records, and verification routes.",
    routes: ["POST /api/kernel/master with certify=true", "POST /api/lyrics/certify", "POST /api/v1/verify", "GET /api/court-cert/:certId"],
    rights: "Evidence can support a claim; it does not create a claim. AI-generated instrumental material can have provider-specific restrictions, and uploaded third-party material remains subject to its license.",
    limitations: ["No technical system guarantees exclusivity or prevents independent similarity.", "A certificate is not copyright registration, legal advice, or a court judgment."],
  },
  {
    slug: "legal-quotations",
    title: "Legal quotations and practical meaning",
    eyebrow: "Reference 23",
    summary: "Selected U.S. Copyright Act language relevant to original works, exclusive rights, registration, rights-management information, and service response.",
    status: "Policy",
    functions: ["Read the source language", "Connect each provision to a product workflow", "Identify where counsel is required", "Avoid overstating what a certificate proves"],
    howTo: ["Read the quotation and the official citation.", "Use the practical meaning as a product guide, not legal advice.", "Keep the evidence trail described in IP Rights.", "Ask counsel about the law that applies to your specific work and dispute."],
    engine: "This is a reference page, not a processing engine.",
    routes: ["Official source links are provided on this page"],
    rights: "Selected U.S. Copyright Act language (official source: https://www.law.cornell.edu/uscode/text/17):\n\n17 U.S.C. § 102(a): “Copyright protection subsists, in accordance with this title, in original works of authorship fixed in any tangible medium of expression, now known or later developed, from which they can be perceived, reproduced, or otherwise communicated, either directly or with the aid of a machine or device.” This is why the service preserves fixed drafts, recordings, source files, and exports; fixation alone does not prove that the uploader owned every element.\n\n17 U.S.C. § 106: “Subject to sections 107 through 122, the owner of copyright under this title has the exclusive rights to do and to authorize any of the following: (1) to reproduce the copyrighted work in copies or phonorecords; (2) to prepare derivative works based upon the copyrighted work; (3) to distribute copies or phonorecords of the copyrighted work to the public by sale or other transfer of ownership, or by rental, lease, or lending; (4) in the case of literary, musical, dramatic, and choreographic works, pantomimes, and motion pictures and other audiovisual works, to perform the copyrighted work publicly; (5) in the case of literary, musical, dramatic, and choreographic works, and pictorial, graphic, or sculptural works, including the individual images of a motion picture or other audiovisual work, to display the copyrighted work publicly; and (6) in the case of sound recordings, to perform the copyrighted work publicly by means of a digital audio transmission.” This is why users must have authorization for every backing track, sample, lyric, and performance they upload.\n\n17 U.S.C. § 411(a): “Except for an action brought under section 1498 of title 28, and subject to subsection (b), no civil action for infringement of the copyright in any United States work shall be instituted until preregistration or registration of the copyright claim has been made in accordance with this title.” A GravelKing certificate is not a Copyright Office registration and does not replace this requirement.\n\n17 U.S.C. § 1202(a): “No person shall knowingly, and with the intent to induce, enable, facilitate, or conceal infringement—(1) provide copyright management information that is false, or (2) distribute or import for distribution copyright management information that is false.” This is why users may not submit false artist, ownership, or certificate information.\n\n17 U.S.C. § 1202(b): “No person shall, without the authority of the copyright owner or the law—(1) intentionally remove or alter any copyright management information.” This is one reason the service records verification state and treats tampering or false provenance as a serious service violation.\n\n17 U.S.C. § 506(a)(1): “Any person who willfully infringes a copyright shall be punished as provided under section 2319 of title 18, if the infringement was committed—(A) for purposes of commercial advantage or private financial gain; (B) by the reproduction or distribution, including by electronic means, during any 180-day period, of 1 or more copies or phonorecords of 1 or more copyrighted works, which have a total retail value of more than $1,000; or (C) by the distribution of a work being prepared for commercial distribution, by making it available on a computer network accessible to members of the public, if such person knew or should have known that the work was being prepared for commercial distribution.” The service does not decide whether conduct meets this standard; it can restrict service access when it reasonably suspects unauthorized or abusive conduct.\n\nThese quotations are educational and should be checked against the current official text with qualified counsel. They do not create rights, prove infringement, or guarantee a legal outcome.",
    limitations: ["The quoted provisions are not a complete legal analysis.", "Statutes, regulations, case law, and facts change; use the official source and qualified counsel."],
  },
  {
    slug: "evidence-status",
    title: "Evidence and current status",
    eyebrow: "Reference 24",
    summary: "A direct status ledger for what is implemented, what has passed local tests, what was checked publicly, and what is still unconfirmed.",
    status: "Live",
    functions: ["See evidence labels", "Separate local tests from public-live proof", "Review known limitations", "Avoid presenting unverified work as complete"],
    howTo: ["Treat Live as a public endpoint or page check, not as a promise that every path was exercised.", "Treat Tested locally as an end-to-end project test.", "Treat Implemented as code present but not necessarily production-proven.", "Treat Unknown as a deliberate stop on unsupported claims."],
    engine: "Evidence classification based on project tests, browser verification, route inspection, and public deployment checks.",
    routes: ["GET /api/healthz", "GET /api/auth/user", "GET /api/subscription/status", "POST /api/kernel/master"],
    rights: "An honest evidence record protects users from relying on an unsupported ownership or service claim.",
    limitations: ["The dedicated Diffin audio arrangement-diff engine is not confirmed as production-live.", "The public demo login route requires a new publish before it can be used by Play reviewers."],
  },
];

export const helpTopicBySlug = new Map(helpTopics.map((topic) => [topic.slug, topic]));