import { Router, type IRouter } from "express";
import healthRouter from "./health";
import kernelRouter from "./kernel";
import audioRouter from "./audio";
import studioRouter from "./studio-mix";
import masterRouter from "./master";
import stripeRouter from "./stripe";
import playBillingRouter from "./playBilling";
import authRouter from "./auth";
import historyRouter from "./history";
import downloadRouter from "./download";
import beatsRouter from "./beats";
import waitlistRouter from "./waitlist";
import analyticsRouter from "./analytics";
import mlkRouter from "./mlk";
import { mlkGenerateRouter } from "./mlkGenerate";
import tracksRouter from "./tracks";
import storageRouter from "./storage";
import adminAuthRouter from "./adminAuth";
import activateRouter from "./activate";
import convertRouter from "./convert";
import lyricsRouter from "./lyrics";
import adminLabelRouter from "./adminLabel";
import courtCertRouter from "./court-cert";
import verifySignalRouter from "./verify-signal";
import leadCaptureRouter from "./lead-capture";
import weekendSpecialRouter from "./weekend-special";
import emailCaptureRouter from "./email-capture";
import benchmarkRouter from "./benchmark";
import referralsRouter from "./referrals";
import investorsRouter from "./investors";
import promoRouter from "./promos";
import jaxRouter from "./jax";

const router: IRouter = Router();

router.use(adminAuthRouter);
router.use(authRouter);
router.use(healthRouter);
router.use(kernelRouter);
router.use(audioRouter);
router.use(studioRouter);
router.use(masterRouter);
router.use(courtCertRouter);
router.use(stripeRouter);
router.use(playBillingRouter);
router.use(historyRouter);
router.use(downloadRouter);
router.use(beatsRouter);
router.use(waitlistRouter);
router.use(analyticsRouter);
router.use(mlkRouter);
router.use(mlkGenerateRouter);
router.use(tracksRouter);
router.use(storageRouter);
router.use(activateRouter);
router.use(convertRouter);
router.use(lyricsRouter);
router.use(adminLabelRouter);
router.use(verifySignalRouter);
router.use(leadCaptureRouter);
router.use(weekendSpecialRouter);
router.use(emailCaptureRouter);
router.use(benchmarkRouter);
router.use(referralsRouter);
router.use(investorsRouter);
router.use(promoRouter);
router.use(jaxRouter);

export default router;
