export default function SearchVerify() {
  return <div className="relative w-screen h-screen overflow-hidden bg-gradient-to-br from-[#fafbfc] to-[#eef4f5] p-[4vh_4vw] font-body text-primary">
    <div className="flex justify-between border-b border-[#dbe4ea] pb-[2vh] text-[1.5vw] font-bold"><span>GRAVELKING PRO</span><span className="text-muted">SEARCH + VERIFICATION · 08</span></div>
    <h1 className="mt-[4vh] text-[4vw] font-extrabold">How search and verification work</h1><p className="mt-[1vh] text-[1.8vw] text-muted">Discovery helps a creator find a track; verification checks whether a signal matches a server record.</p>
    <div className="mt-[5vh] grid grid-cols-2 gap-[2vw]">
      <div className="rounded-[1.2vw] bg-white p-[3vh_2.4vw] ring-1 ring-[#dbe4ea]"><div className="flex items-center gap-[1vw]"><span className="rounded-full bg-[#d1fae5] px-[1vw] py-[.8vh] text-[1.4vw] font-bold text-emerald-700">DISCOVERY</span><span className="text-[2vw] text-muted">→</span></div><h2 className="mt-[2vh] text-[2.7vw] font-extrabold">Search + singing</h2><p className="mt-[2vh] text-[1.7vw] leading-[1.45] text-muted">Lyrics search uses catalog lookup and synced LRC when available. Energy timing is an honest approximate fallback.</p><p className="mt-[2vh] text-[1.55vw] font-bold text-accent">Vocal Booth: record, effects, backing track, timed/scrolled lyrics.</p></div>
      <div className="rounded-[1.2vw] bg-primary p-[3vh_2.4vw] text-white"><div className="flex items-center gap-[1vw]"><span className="rounded-full bg-[#134e4a] px-[1vw] py-[.8vh] text-[1.4vw] font-bold text-[#99f6e4]">PROOF</span><span className="text-[2vw] text-[#5eead4]">→</span></div><h2 className="mt-[2vh] text-[2.7vw] font-extrabold">Signal verification</h2><p className="mt-[2vh] text-[1.7vw] leading-[1.45] text-white/70">Public verification extracts the watermark, finds the server record, and validates HMAC plus content hash.</p><p className="mt-[2vh] text-[1.55vw] font-bold text-[#5eead4]">Verification endpoints: /api/kernel/verify-signal and /api/v1/verify</p></div>
    </div>
    <div className="mt-[4vh] rounded-[1vw] border border-amber-200 bg-amber-50 p-[2.3vh_2vw] text-[1.65vw] font-bold text-amber-800">AMBER — Keep the whitepaper specification aligned with the actual owner-only, unlock-gated certificate routes.</div>
    <div className="absolute bottom-[3vh] left-[4vw] right-[4vw] flex justify-between border-t border-[#dbe4ea] pt-[1.5vh] text-[1.5vw] text-muted"><span>Search is not proof; the signal is proof</span><span>Confidential · 08</span></div>
  </div>;
}