/**
 * GravelKing IP Certificate Stubs — server-side denominator storage.
 *
 * Every mastered track gets a cert split into two halves:
 *   - Nominator  → embedded in the audio file's LSB watermark (track carries it)
 *   - Denominator → stored here (server keeps it, never leaves the server)
 *
 * Verification requires BOTH halves.  Neither alone proves anything.
 * The HMAC handshake can only be regenerated by this server (SESSION_SECRET).
 * This makes server-verified ownership the only path to a valid cert —
 * legally admissible as a timestamped, server-authoritative IP record.
 */
import { pgTable, text, timestamp, integer } from "drizzle-orm/pg-core";

export const ipCertStubsTable = pgTable("ip_cert_stubs", {
  /** UUID — embedded in the track as the lookup key */
  certId:       text("cert_id").primaryKey(),

  /** SHA-256(contentHash|artist|certId)[32:] — the server half of the full hash */
  denominator:  text("denominator").notNull(),

  /** HMAC-SHA256(certId|nominator|denominator, SESSION_SECRET) — server-only proof */
  handshake:    text("handshake").notNull(),

  /** SHA-256 of the pre-MLK audio content — ground truth for this cert */
  contentHash:  text("content_hash").notNull(),

  /** Artist handle bound to this cert at certification time */
  artist:       text("artist").notNull(),

  /** When the cert was created on the server — the legally relevant timestamp */
  certifiedAt:        timestamp("certified_at", { withTimezone: true }).notNull().defaultNow(),

  /** The style/instrumental prompt the artist wrote — evidence of creative direction */
  stylePrompt:        text("style_prompt"),

  /** 0–100 human-authorship score derived from the style prompt specificity */
  styleAuthorshipScore: integer("style_authorship_score"),

  // ── Global Music Industry Identifiers (optional, artist-supplied) ────────
  // Binding these to the cryptographic cert ties the IDs to the
  // server-authoritative ownership record in a tamper-evident way.

  /** IPI (Interested Party Information) — songwriter/composer registry ID */
  ipiNumber: text("ipi_number"),

  /** ISWC (International Standard Work Code) — composition identifier */
  iswc: text("iswc"),

  /** ISRC (International Standard Recording Code) — recording identifier */
  isrc: text("isrc"),

  // ── Certificate paywall (task: docs stay private until unlocked) ────────

  /** Owning user (users.id) — the ONLY account allowed to view/unlock docs.
   *  NULL = legacy stub with no recorded owner → fail closed (no access). */
  ownerUserId: text("owner_user_id"),

  /** What was certified: 'lyrics' | 'instrumental' | 'full_track' | 'vocal_performance' */
  category: text("category"),

  /** Name of the generating AI model (e.g. 'lyria-3-pro-preview').
   *  NULL = human performance / external upload (no AI generation). */
  generationModel: text("generation_model"),

  /** Commercial-catalog copyright screen result at certification time:
   *  'no_match' | 'match' | 'unavailable' | 'not_run'. NULL = legacy stub
   *  created before the result was persisted on the cert. */
  fingerprintStatus: text("fingerprint_status"),

  /** Copyright-screen provider (currently 'acrcloud'). */
  fingerprintProvider: text("fingerprint_provider"),

  /** When the copyright screen ran. NULL = legacy stub or scan not run. */
  fingerprintScannedAt: timestamp("fingerprint_scanned_at", { withTimezone: true }),

  /** Where the audio came from: 'internal' (generated in-app) |
   *  'external_upload' (user upload, ACRCloud-gated) | 'vocal_recording' (in-app booth) */
  provenance: text("provenance"),

  /** When the certificate DOCUMENT was unlocked (NULL = still locked).
   *  Stamping is free; the JSON/PDF document is the paid artifact. */
  unlockedAt: timestamp("unlocked_at", { withTimezone: true }),

  /** How it was unlocked: 'purchase' ($1.99 one-time) | 'included' (subscriber allowance) | 'admin' */
  unlockSource: text("unlock_source"),

  /** Stripe Checkout session that paid for this unlock — idempotency anchor
   *  for duplicate webhook deliveries. */
  stripeSessionId: text("stripe_session_id"),
});
